import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'


export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Movies-Next-Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav />
      <Results results = {results} />
    </div>
  )
}

const BASE_URL = 'https://api.themoviedb.org/3'
console.log(BASE_URL)

export async function getServerSideProps(context){
  const genre = context.query.genre;
  const request = await fetch(BASE_URL + (requests[genre]?.url || requests.fetchTrending.url));
  const objJSON = await request.json();

  return {
    props: {
      results: objJSON.results
    }
  }
}
